
bungeecord:
  enable: true
  server-name: server1

redis:
  enable: true
  password: nothing
  address: localhost
  port: 6379

kubernetes:
  enable: true

#----------# for bungeecord #---------- #
enable-lobby : true
enable-minigame : true
#----------# for bungeecord #----------#

# it's a essential option
lobby-location:
  ==: org.bukkit.Location
  world: world
  x: 0
  y: 64
  z: 0
  yaw : 0
  pitch : 0