name: Quantium
main: org.netherald.quantium.QuantiumPlugin
version: 1.0
softdepend:
  - Multiverse-Core
  - Multiverse-NetherPortals
commands:
  quantiumbukkit:
    aliases:
      - qb
    description: Quantium comman
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.31
  - org.jetbrains.kotlin:kotlin-reflect:1.5.31
  - io.lettuce:lettuce-core:6.1.5.RELEASE