name: Quantium
main: org.netherald.quantium.QuantiumPlugin
version: 1.0
depend:
  - Kotlin
softdepend:
  - Multiverse-Core
  - Multiverse-NetherPortals
commands:
  quantiumbukkit:
    aliases:
      - qb
    description: Quantium command